"""Initial_migration

Revision ID: 65477c26ba36
Revises: 
Create Date: 2026-02-16 17:41:25.922077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65477c26ba36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_audit_logs')
    op.alter_column('courses', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='course_status'),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='coursestatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'DRAFT'::course_status"))
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'courses', 'users', ['user_id'], ['id'])
    op.alter_column('enrollments', 'purchased_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('enrollments_user_id_course_id_key'), 'enrollments', type_='unique')
    op.alter_column('instructor_profiles', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('lessons', 'section_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('lessons', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('lessons', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('lessons_section_id_order_index_key'), 'lessons', type_='unique')
    op.drop_column('lessons', 'content_type')
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('reviews_user_id_course_id_key'), 'reviews', type_='unique')
    op.drop_constraint(op.f('sections_course_id_order_index_key'), 'sections', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('sections_course_id_order_index_key'), 'sections', ['course_id', 'order_index'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('reviews_user_id_course_id_key'), 'reviews', ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('lessons', sa.Column('content_type', postgresql.ENUM('VIDEO', 'ARTICLE', 'QUIZ', name='content_type'), server_default=sa.text("'VIDEO'::content_type"), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('lessons_section_id_order_index_key'), 'lessons', ['section_id', 'order_index'], postgresql_nulls_not_distinct=False)
    op.alter_column('lessons', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lessons', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('lessons', 'section_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('instructor_profiles', 'verified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(op.f('enrollments_user_id_course_id_key'), 'enrollments', ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('enrollments', 'purchased_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.alter_column('courses', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='coursestatus'),
               type_=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='course_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'DRAFT'::course_status"))
    op.create_table('course_audit_logs',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('previous_status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='course_status'), autoincrement=False, nullable=True),
    sa.Column('new_status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='course_status'), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('course_audit_logs_admin_id_fkey')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_audit_logs_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_audit_logs_pkey'))
    )
    # ### end Alembic commands ###
